# Generated by Django 5.2.16 on 2026-07-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_seed_tipos_estudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('procesada', 'Procesada'), ('ausente', 'Ausente')], default='agendada', max_length=20),
        ),
    ]
