# Generated by Django 5.2.16 on 2026-08-03 21:40

import django.db.models.deletion
import pacientes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_paciente_expediente_alter_cita_estado_cambiocita'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='expediente_igss',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Expediente IGSS (opcional)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=100, validators=[pacientes.models.validar_nombre_apellido]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dpi',
            field=models.CharField(max_length=20, unique=True, validators=[pacientes.models.validar_dpi_guatemala], verbose_name='DPI'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='expediente',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, verbose_name='No. Expediente Interno'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=100, validators=[pacientes.models.validar_nombre_apellido]),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('coex', 'COEX'), ('igss', 'IGSS'), ('emergencia', 'Emergencia')], max_length=20)),
                ('prioridad', models.PositiveSmallIntegerField(choices=[(1, 'Normal'), (2, 'Alta'), (3, 'Emergencia')], default=1)),
                ('estado', models.CharField(choices=[('en_espera', 'En Espera'), ('en_proceso', 'En Proceso'), ('reagendado', 'Reagendado'), ('ausente', 'Ausente'), ('completado', 'Completado')], default='en_espera', max_length=20)),
                ('numero_diario', models.PositiveIntegerField(default=0, editable=False)),
                ('turno', models.CharField(blank=True, editable=False, max_length=20)),
                ('hora_llegada', models.DateTimeField(blank=True, null=True)),
                ('hora_llamado', models.DateTimeField(blank=True, null=True)),
                ('hora_inicio_estudio', models.DateTimeField(blank=True, null=True)),
                ('hora_fin_estudio', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='pacientes.cita')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'db_table': 'tickets',
                'ordering': ['-prioridad', 'hora_llegada'],
            },
        ),
        migrations.CreateModel(
            name='TicketCambioEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('prioridad_anterior', models.PositiveSmallIntegerField()),
                ('prioridad_nueva', models.PositiveSmallIntegerField()),
                ('razon', models.TextField(blank=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='pacientes.ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cambio de estado de ticket',
                'verbose_name_plural': 'cambios de estado de ticket',
                'db_table': 'tickets_cambios_estado',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
