# Generated by Django 5.2.16 on 2026-07-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='hora_llegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
