# Generated by Django 5.2.16 on 2026-07-28 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_cita_hora_llegada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('en_proceso', 'En proceso'), ('procesada', 'Procesada'), ('ausente', 'Ausente')], default='agendada', max_length=20),
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='motivo / indicación clínica')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='orden_trabajo', to='pacientes.cita')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'orden de trabajo',
                'verbose_name_plural': 'órdenes de trabajo',
                'db_table': 'ordenes_trabajo',
                'ordering': ['creada_en'],
            },
        ),
    ]
