# Generated by Django 5.2.16 on 2026-07-31 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_paciente_sexo_alter_cita_estado_ordentrabajo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='informe_archivo',
            field=models.FileField(blank=True, null=True, upload_to='informes/%Y/%m/', verbose_name='informe (archivo)'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='informe_creado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='informe_creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='informes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='informe_texto',
            field=models.TextField(blank=True, verbose_name='informe (texto)'),
        ),
        migrations.CreateModel(
            name='ImagenEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='imagenes_estudio/%Y/%m/')),
                ('subida_en', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='pacientes.ordentrabajo')),
                ('subida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imagenes_subidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'imagen de estudio',
                'verbose_name_plural': 'imágenes de estudio',
                'db_table': 'imagenes_estudio',
                'ordering': ['subida_en'],
            },
        ),
    ]
