# Generated by Django 5.2.16 on 2026-08-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_alter_ticket_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('ultimo', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'secuencia diaria',
                'verbose_name_plural': 'secuencias diarias',
                'db_table': 'daily_sequences',
                'unique_together': {('servicio', 'fecha')},
            },
        ),
    ]
