# Generated by Django 5.2.16 on 2026-08-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_cita_fecha_sugerida_cita_hora_sugerida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoestudio',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
