# Generated by Django 5.2.16 on 2026-08-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_tipoestudio_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoestudio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
