# Generated by Django 5.2.16 on 2026-08-08 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0012_asignar_radiologo_pendientes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('ultimo', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'secuencia diaria de tickets',
                'verbose_name_plural': 'secuencias diarias de tickets',
                'db_table': 'secuencias_diarias_tickets',
                'unique_together': {('servicio', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('coex', 'COEX'), ('privado', 'Privado'), ('emergencia_igss', 'Emergencia IGSS')], max_length=20)),
                ('prioridad', models.PositiveSmallIntegerField(choices=[(1, 'Normal'), (2, 'Urgente'), (3, 'Crítica')], default=1)),
                ('estado', models.CharField(choices=[('en_espera', 'En espera'), ('en_atencion', 'En atención'), ('atendido', 'Atendido'), ('ausente', 'Ausente')], default='en_espera', max_length=20)),
                ('numero', models.PositiveIntegerField(default=0, editable=False)),
                ('turno', models.CharField(blank=True, editable=False, max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='motivo de la visita')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('atendido_en', models.DateTimeField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='pacientes.paciente')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'db_table': 'tickets',
                'ordering': ['-prioridad', 'creado_en'],
            },
        ),
    ]
