# Generated by Django 5.2.16 on 2026-08-08 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0013_dailysequence_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cita',
            field=models.ForeignKey(blank=True, help_text='Cita/orden de trabajo generada al procesar este ticket (si ya se procesó).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_origen', to='pacientes.cita'),
        ),
    ]
