# Generated by Django 5.2.16 on 2026-08-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0015_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='informe_actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='informe_estado',
            field=models.CharField(default='PENDIENTE', max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='historial_clinico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
