# Generated by Django 5.2.16 on 2026-08-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0015_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
