# Generated by Django 5.2.16 on 2026-08-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0016_ordentrabajo_informe_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='informe_version',
            field=models.IntegerField(default=1),
        ),
    ]
