# Generated by Django 5.2.16 on 2026-08-18 15:18

import pacientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0017_ordentrabajo_informe_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenestudio',
            options={},
        ),
        migrations.AlterField(
            model_name='imagenestudio',
            name='archivo',
            field=models.FileField(upload_to=pacientes.models.ruta_imagenes_estudio),
        ),
        migrations.AlterModelTable(
            name='imagenestudio',
            table=None,
        ),
    ]
