# Generated by Django 5.2.16 on 2026-07-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_traducir_tablas_django'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('recepcionista', 'Recepcionista'), ('tecnico_imagenes', 'Técnico de imágenes'), ('medico_radiologo', 'Médico radiólogo'), ('medico_remitente', 'Médico remitente')], default='administrador', max_length=20, verbose_name='rol'),
        ),
    ]
