# Generated by Django 5.2.16 on 2026-08-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='porcentaje_coex',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% comisión COEX'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='porcentaje_emergencia_igss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% comisión emergencia IGSS'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='porcentaje_privado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% comisión privado'),
        ),
    ]
