# Generated by Django 5.2.16 on 2026-08-04 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usuario_porcentaje_coex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_intento', models.CharField(blank=True, max_length=150)),
                ('accion', models.CharField(choices=[('login_exitoso', 'Inicio de sesión'), ('login_fallido', 'Intento de inicio de sesión fallido'), ('crear_usuario', 'Creación de usuario'), ('crear_estudio', 'Creación de estudio'), ('solicitar_cita', 'Solicitud de cita'), ('confirmar_cita', 'Confirmación de cita'), ('rechazar_cita', 'Rechazo de solicitud de cita'), ('reagendar_cita', 'Reagenda de cita'), ('marcar_llegada', 'Llegada de paciente'), ('marcar_ausente', 'Ausencia de paciente'), ('generar_orden', 'Generación de orden de trabajo'), ('adjuntar_imagenes', 'Carga de imágenes de estudio'), ('adjuntar_informe', 'Carga de informe')], max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_bitacora', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento de bitácora',
                'verbose_name_plural': 'bitácora',
                'db_table': 'bitacora',
                'ordering': ['-creado_en'],
            },
        ),
    ]
