# Generated by Django 5.2.16 on 2026-08-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_paciente_expediente_igss_alter_paciente_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='servicio',
            field=models.CharField(choices=[('coex', 'COEX'), ('privado', 'Privado'), ('igss', 'IGSS'), ('emergencia', 'Emergencia')], max_length=20),
        ),
    ]
