# Generated by Django 5.2.16 on 2026-08-08 00:40

import pacientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_dailysequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, validators=[pacientes.models.validar_nombre_apellido]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dpi',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[pacientes.models.validar_dpi_guatemala], verbose_name='DPI'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, validators=[pacientes.models.validar_nombre_apellido]),
        ),
    ]
