# Generated by Django 5.2.16 on 2026-07-30 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_seed_tipos_estudio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='expediente',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de expediente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('procesada', 'Procesada'), ('cancelada', 'Cancelada')], default='agendada', max_length=20),
        ),
        migrations.CreateModel(
            name='CambioCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('cancelar', 'Cancelar'), ('reprogramar', 'Reprogramar')], max_length=20)),
                ('motivo', models.TextField()),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='pacientes.cita')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cambio de cita',
                'verbose_name_plural': 'cambios de cita',
                'db_table': 'cambios_cita',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
